name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build

      # ビルドファイルの確認
      - name: Check build files
        run: |
          ls -la dist/
          ls -la dist/main/

      # Mac用のビルド
      - name: Build Mac App
        if: matrix.os == 'macos-latest'
        run: |
          npm run package-mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Windows用のビルド
      - name: Build Windows App
        if: matrix.os == 'windows-latest'
        run: |
          npm run package-windows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # GitHub Releaseの作成
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.dmg
            dist/*.zip
            dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 